openapi: "3.0.0"
info:
  version: 1.0.0
  title: "Baby Billing API"
  license:
    name: MIT
servers:
  - url: http://localhost:8765
tags:
  - name: subscriber
    description: 'Абонент'
  - name: manager
    description: 'Менеджер'

paths:
  /brt/api/subscriber/{msisdn}/pay:
    patch:
      tags:
        - subscriber
      summary: Пополнение баланса
      operationId: toUpBalance
      description: Пополнение баланса абонентом на введенную сумму
      security:
        - subscriber_auth: [ ]
      parameters:
        - name: msisdn
          in: path
          description: Номер телефона абонента
          required: true
          schema:
            type: integer
            example: 79007770303
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopUpDTO'
      responses:
        '200':
          description: Баланс успешно пополнен
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Некорректная сумма или сумма меньше минимальной (0.1 у.е.)
          content:
            text/plain:
              schema:
                type: string
        '404':
          $ref: '#/components/responses/NotFound'
          content:
            text/plain:
              schema:
                type: string
        '403':
          description: Абонент не авторизирован
          content:
            text/plain:
              schema:
                type: string
        '5XX':
          $ref: '#/components/responses/ServerError'

  /brt/api/subscriber/{msisdn}/changeTariff:
    patch:
      tags:
        - manager
      summary: Смена тарифного плана абонента
      security:
        - manager_auth: []
      operationId: changeTariff
      description: Позволяет менеджеру сменить тариф абоненту
      parameters:
        - name: msisdn
          in: path
          description: Номер телефона абонента
          required: true
          schema:
            type: integer
            example: 79007770303
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeTariffDTO'
      responses:
        '200':
          description: Тариф успешно изменен
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Некорректный идентификатор тарифа
          content:
            text/plain:
              schema:
                type: string
        '403':
          $ref: '#/components/responses/InvalidAuth'
        '409':
          description: Абонент 79007770303 уже пользуется данным тарифом
        '404':
          $ref: '#/components/responses/NotFound'
          content:
            text/plain:
              schema:
                type: string
        '5XX':
          $ref: '#/components/responses/ServerError'

  /brt/api/subscriber/save:
    post:
      tags:
        - manager
      summary: Добавление нового абонента
      operationId: addNewClient
      security:
        - manager_auth: []
      description: "Добавление нового абонента с параметрами: номер телефона, тариф, баланс"
      responses:
        '200':
          description: Новый абонент успешно добавлен
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Номер телефона / Тариф введен некорректно
          content:
            text/plain:
              schema:
                type: string
        '403':
          $ref: '#/components/responses/InvalidAuth'
          content:
            text/plain:
              schema:
                type: string
        '409':
          description: Абонент уже является клиентом Ромашки
        '5XX':
          $ref: '#/components/responses/ServerError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscriber'
  /api/start:
    post:
      tags:
        - CDR
      summary: Запуск генератора CDR
      operationId: startCDR
      responses:
        '200':
          description: Генератор CDR запущен
        '5XX':
          $ref: '#/components/responses/ServerError'
  /api/register:
    post:
      tags:
        - CDR
      summary: Добавление стоп-поинта
      responses:
        '200':
          description: Стоп-поинт добавлен
        '5XX':
          $ref: '#/components/responses/ServerError'
  /api/deregister:
    post:
      tags:
        - CDR
      summary: Удаление стоп-поинта
      responses:
        '200':
          description: Стоп-поинт удален
        '5XX':
          $ref: '#/components/responses/ServerError'
  /api/iterate:
    post:
      tags:
        - CDR
      summary: Выполнение одного шага генерации до следующего месяца
      responses:
        '200':
          description: Шаг генерации выполнен
        '5XX':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    TopUpDTO:
      type: object
      required:
        - money
      properties:
        money:
          type:  number
          description: Сумма пополнения
          format: float
          example: 100.1
    Subscriber:
      type: object
      properties:
        msisdn:
          type: integer
          description: Номер абонента
          format: int64
          example: 79007770303
        tariffId:
          type: integer
          description: ID тарифа абонента
          format: int64
          example: 11
    ChangeTariffDTO:
      type: object
      required:
        - tariffId
      properties:
        tariffId:
          type: integer
          description: Новый ID тарифа абонента
          format: int64
          example: 11
  responses:
    ServerError:
      description: Ошибка сервера при обработке запроса
    NotFound:
      description: Абонент не является клиентом Ромашки - 79007770303
    InvalidAuth:
      description: Менеджер не авторизирован
  securitySchemes:
    manager_auth:
      type: http
      scheme: basic
      description: Авторизация менеджера с указанием логина и пароля
    subscriber_auth:
      type: http
      scheme: basic
      description: Авторизация абонента с указанием логина